### ISSUE TITLE
YouTube Buffering?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [DesktopECHO/kWSL#8] opened 2021-04-12 15:10 UTC
First let me say what a fantastic piece of work this is...I love KDE and I love WSL so this solution is/was perfect for me...

Sound quality in kWSL is also fantastic...one quetion though. It seems when i try to use something like YouTube inside kWSL i see a lot of what appears to be buffering, i.e a fairly health amount of time with the spinner going before the actual video starts. I can switch over to my main Windows desktop, fire up the same video(s) and there is no such problem...

Any ideas as to what might be causing this with kWSL?

**Comment by DesktopECHO** [comment] 2021-04-12 15:30
Hi Mike,

I notice the same buffering issue on YouTube.  

Unfortunately I don't know the cause at this time -- The issue doesn't occur when starting a session using Chrome Remote Desktop so it's something to do with xRDP/PulseAudio. 

Performance of CRD is excellent over local connections and it's preinstalled, you may want to give that a try for your use case:
https://github.com/DesktopECHO/kWSL/wiki/Enable-Chrome-Remote-Desktop

If I get some free time I'll have another go at this issue -- It's bothersome to me as well.   One thing I haven't checked is if the issue appears in WSL2 as well or only in WSL1.

Always nice to hear from folks using kWSL, thanks for the kind words.
Cheers,
D.

**Comment by mfreeman-xtivia** [comment] 2021-04-15 02:25
I tried the Chrome Desktop but for me anyway the visual experience just isn't nearly as nice as using RDP

**Comment by mfreeman-xtivia** [comment] 2021-04-15 02:26
Also meant to ask earlier, do you also see this problem in xWSL as well?

**Comment by DesktopECHO** [comment] 2021-04-18 02:15
Yes, the YouTube pause-before-playback issue appears in both xWSL and kWSL — But I believe only when run on WSL1.  I’ll need to verify that...

**Comment by mfreeman-xtivia** [comment] 2021-04-19 15:33
FWIW i did a test this morning against a fresh WSL1 based version, using SeaMonkey, and the YouTube lag is there as well.

**Comment by mfreeman-xtivia** [comment] 2021-06-20 12:23
So FWIW this buffering issue seems to be gone in the latest version of kWSL.

Sadly it still seems to be present in the latest version of xWSL.

Any differences between them in terms of xrdp?

**Comment by DesktopECHO** [comment] 2021-06-22 17:04
Hi Mike,

Not sure what's going on, but things work better when I reload the YouTube page in Seamonkey.  

What I'm seeing is that after reloading the page on xWSL/kWSL, I don't get the 7-second pause when you change to a differnt time in the video.

This is definitely a change in behaviour from a few weeks ago.  I'm trying to track down what update made this change, but it's good news!

**Comment by mfreeman-xtivia** [comment] 2021-06-23 22:07
There seems to be a certain hit or miss quality to this which is maddening...i now have an instance of kWSL where Firefox lags on YouTube, but Chrome does not! grrrrrrrrr

**Comment by DesktopECHO** [comment] 2021-06-30 14:09
Try installing the latest kWSL build I pushed to get Konqueror running (which is Chromium-based) and let me know how things look on your end.

**Comment by mfreeman-xtivia** [comment] 2021-07-08 18:43
Nice...

One piece of bad news here though is that it appears that kWSL won't install at all on newer versions of Windows. I installed the preview version of Windows 11 and see this behavior, and was also seeing it on even Insider versions of Windows 10.

**Comment by DesktopECHO** [comment] 2021-07-08 19:01
What kind of error do you run into?  I’m not worried; if there’s some issue with Windows 11 I don’t see forsee any issues that can’t be worked around.

**Comment by mfreeman-xtivia** [comment] 2021-07-08 19:03
The installation blows through very quickly and emits a bunch of errors  about not being able to find the named WSL instance.

**Comment by DesktopECHO** [comment] 2021-07-08 19:08
Thanks for the info, I’ll sort that out when Windows 11 gets closer to completion.  In the meantime, we can close this issue as Falkon/Konqueror seem to work perfectly on WSL1 now.

**Comment by mfreeman-xtivia** [comment] 2021-07-12 16:35
FWIW the root issue is the following error; I have been seeing this error even in Preview versions of 10.X prior to Windows 11. Don't know if they moved/removed the registry key in question...

`Couldn't get the value "DistributionName" of the registry key "Software\Microsoft\Windows\CurrentVersion\Lxss\AppxInstallerCache".`

![image](https://user-images.githubusercontent.com/10734467/125325845-069a8c00-e307-11eb-9a4c-2ac13c269f45.png)

**Comment by DesktopECHO** [comment] 2021-07-15 22:12
Hi Mike,

I can install xWSL/kWSL on the latest build of Windows 11 (22000.65) without issue.

**Comment by mfreeman-xtivia** [comment] 2021-07-15 22:19
This is so weird. Let me see if i can dig up any more details

**Comment by mfreeman-xtivia** [comment] 2021-07-15 22:36
Does that reg entry "Software\Microsoft\Windows\CurrentVersion\Lxss\AppxInstallerCache" have a specific/expected value on your system?

And do you where/what script would be spitting this out...

There is no distribution with the supplied name.
There is no distribution with the supplied name.
There is no distribution with the supplied name.
There is no distribution with the supplied name.
There is no distribution with the supplied name.
There is no distribution with the supplied name.
There is no distribution with the supplied name.

**Comment by DesktopECHO** [comment] 2021-07-15 23:51
I don't have an AppxInstallerCache entry.  The install fails very early in the script for you; all this unexpected outpt you see is due to the base Ubuntu distro not getting installed properly with LxRunOffline.exe. 

Closest thing I can see to your issue is [here](https://githubmemory.com/repo/DDoSolitary/LxRunOffline/issues?cursor=Y3Vyc29yOnYyOpK5MjAyMC0xMi0yMlQxODo0MToxNSswODowMM4uEJ94&pagination=prev&page=1).  You should try this with a clean Windows 11 install ("Reset This PC" in System Settings.)  I suspect there is some cruft in the registry that's causing the problem.  

I'm going to re-close this issue as it has nothing to do with YouTube buffering, but please feel free to open a new issue if you see this in a fresh install. 

![image](https://user-images.githubusercontent.com/33142753/125870881-1a01916b-250f-4c27-92a5-41559d7eb695.png)

**Closed as completed by DesktopECHO** 2021-07-15 23:51 UTC

**Comment by mfreeman-xtivia** [comment] 2021-07-16 00:13
FWIW and just to close the loop on this one...

Turned echo back on in the install script to trace where it was actually dying--turned out to be (as you suspected) the first place where LxRunOffline attempts to install the downloaded distro. The error is apparently buried inside LxRunOffline--grokking the closed issues in its GitHub repo pointed me to someone who had a very similar problem...the issue turned out to be that particular registry entry above.

It seems its left over from kind of previous Windows Store install attempt and it causes LxRunOffline to puke. The recommendation was to delete the .../AppxInstallerCache entry from the registry and then re-try. That indeed seems to have fixed the issue for me.
